### ISSUE TITLE
Pip shows version 0.5.1 as latest

### ISSUE THREAD

**Issue by Spaz667** [flypenguin/python-cattleprod#1]
Hello!

Thank you for such a quick way to access to rancher API!  I just wanted to let you know that your pip version mismatch the latest version which led to some confusion for me when auth was not part of the signature for poke!

Thanks again!
    Scott

**Comment by flypenguin** [comment]
really bad, but thank you! I'll have a look into it. can do on thursday,
not before, unfortunately.

2016-11-08 21:31 GMT+01:00 Spaz667 <notifications@github.com>:

**Comment by flypenguin** [comment]
Hi Scott, I had a look and I am not sure what you mean. The pip version seems to be 0.6.0, which is also the latest on master, which is also set in all the version flags. Am I missing something?

**Comment by Spaz667** [comment]
Hey Axel,

I'm not sure but when I installed via pip install cattle prod I was getting version 5.1 as the latest one.  Perhaps my pip repository is to blame.

You can close this as it is most likely user environment than an actual issue.

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by flypenguin** [comment]
okay closing this. :) just reopen with more info if it persists.
